task: detection

model: RTDETR
criterion: SetCriterion
postprocessor: RTDETRPostProcessor

RTDETR:
  backbone: PResNet
  encoder: EfficientEncoder
  decoder: RTDETRTransformer
  multi_scale: [640]

PResNet:
  depth: 50
  variant: d
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True

EfficientEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  encoder_feat_strides: [64, 128]
  num_encoder_layers: [1, 1]
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: "gelu"
  pe_temperature: 10000

  # cross
  act: "silu"
  num_bifpn_layers: 7
  # eval
  eval_spatial_size: [640, 640]

RTDETRTransformer:
  feat_channels: [256, 256, 256, 256, 256]
  feat_strides: [8, 16, 32, 64, 128]
  hidden_dim: 256
  num_levels: 5

  num_queries: 300

  num_decoder_layers: 6
  num_denoising: 100

  eval_idx: -1
  eval_spatial_size: [640, 640]

use_focal_loss: True

RTDETRPostProcessor:
  num_top_queries: 300

SetCriterion:
  weight_dict: { loss_vfl: 1, loss_bbox: 5, loss_giou: 2 }
  losses: ["vfl", "boxes"]
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: { cost_class: 2, cost_bbox: 5, cost_giou: 2 }
    # use_focal_loss: True
    alpha: 0.25
    gamma: 2.0
