__include__:
  [
    "../dataset/coco_detection.yml",
    "../runtime.yml",
    "./include/dataloader.yml",
    "./include/optimizer.yml",
    "./include/effdetr_r50vd.yml",
  ]

output_dir: /home/prml/StudentsWork/ChanYoung/Experiments/Eff-detr/output/250603_50vd_6x_coco
