__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd_aux_loss.yml',
]

output_dir: /home/prml/StudentsWork/ChanYoung/Experiments/rtdetr_aux_r50vd_backbone

