task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/work/Dataset/coco2017/train2017/
    ann_file: /home/work/Dataset/coco2017/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 64
  num_workers: 16
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/work/Dataset/coco2017/val2017/
    ann_file: /home/work/Dataset/coco2017/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 64
  num_workers: 16
  drop_last: False