__include__:
  [
    "../dataset/miap_detection.yml",
    "../runtime.yml",
    "./include/dataloader.yml",
    "./include/optimizer.yml",
    "./include/rtdetr_effb0_size640.yml",
  ]

output_dir: /home/prml/StudentsWork/ChanYoung/Experiments/rt_detr/output/rtdetr_effb0_6x_miap_small

EfficientNet:
  model_name: b3

HybridEncoder:
  in_channels: [48, 136, 1536]
  expansion: 0.5

RTDETRTransformer:
  feat_channels: [256, 256, 256]
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100
  hidden_dim: 256

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*backbone)(?=.*norm).*$"
      lr: 0.00001
      weight_decay: 0.
    - params: "^(?=.*backbone)(?!.*norm).*$"
      lr: 0.00001
    - params: "^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$"
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001
