# 실험정보
# 24-07-10
# many2loss를 테스트하기 위한 코드

__include__:
  [
    "../dataset/coco_detection.yml",
    "../runtime.yml",
    "./include/dataloader.yml",
    "./include/optimizer.yml",
    "./include/rtdetr_r50vd_many2one_loss.yml",
  ]

output_dir: /home/prml/StudentsWork/ChanYoung/Experiments/rt_detr/AAAI2025/many2one_loss
