__include__:
  [
    "../dataset/coco_detection.yml",
    "../runtime.yml",
    "./include/dataloader.yml",
    "./include/optimizer.yml",
    "./include/effhy_detr_r50vd.yml",
  ]

output_dir: /home/prml/StudentsWork/ChanYoung/Experiments/EffHybrid-detr/output/250604_50vd_6x_coco
